# imagen base
FROM python:3.7.2-alpine

# instalar dependencias
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# estableciendo working directory
WORKDIR /usr/src/app

# copiando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

#copiando entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh

# copiando app
COPY . /usr/src/app

#ejecutando server
CMD ["sh","-c","chmod 777 /usr/src/app/entrypoint-prod.sh && /usr/src/app/entrypoint-prod.sh"]